/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_zelong_lin_utils_DlibJNIJAVA */

#ifndef _Included_com_zelong_lin_utils_DlibJNIJAVA
#define _Included_com_zelong_lin_utils_DlibJNIJAVA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zelong_lin_utils_DlibJNIJAVA
 * Method:    getLandMarks
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_zelong_lin_utils_DlibJNIJAVA_getLandMarks
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
